CREATE TABLE tbl_admin (
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
);


CREATE TABLE tbl_final (
    id INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    year VARCHAR(100) NOT NULL,
    roll VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    apx VARCHAR(100) NOT NULL,
    qrx VARCHAR(100) NOT NULL,
    apy VARCHAR(100) NOT NULL,
    qry VARCHAR(100) NOT NULL,
    apz VARCHAR(100) NOT NULL,
    qrz VARCHAR(100) NOT NULL
);


CREATE TABLE tbl_latepay (
    id INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    roll VARCHAR(100) NOT NULL,
    year VARCHAR(10) NOT NULL,
    dept VARCHAR(10) NOT NULL,
    email VARCHAR(100) NOT NULL,
    transacinfo VARCHAR(500) NOT NULL,
    payreceiver VARCHAR(100) NOT NULL
);
